name: OctoGuide

on:
  discussion:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - deleted
      - edited
  issue_comment:
    types:
      - created
      - deleted
      - edited
  issues:
    types:
      - edited
      - opened
  pull_request_review_comment:
    types:
      - created
      - deleted
      - edited
  pull_request_target:
    types:
      - edited
      - opened

jobs:
  octoguide:
    if: ${{ !endsWith(github.actor, '[bot]') }}
    permissions:
      discussions: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: JoshuaKGoldberg/octoguide@e2c774d098e6b38c428bcd90dcca254389544aef # 0.21.10
        with:
          config: strict
          github-token: ${{ secrets.GITHUB_TOKEN }}
